const types=[
  {name:'Drone',group:'Aerial',desc:'Ascending, orbiting, and long-range flight',a:'#7298a8',b:'#254e54',media:'drone',wide:true,featured:true},
  {name:'Walking',group:'Ground',desc:'First-person paths through real places',a:'#8caf8e',b:'#315b50',media:'walking',featured:true},
  {name:'Boat',group:'Water',desc:'Waterborne motion at multiple scales',a:'#79aebd',b:'#24526a',media:'boat',wide:true,featured:true},
  {name:'Cable Car',group:'Aerial',desc:'Vertical motion and distant vistas',a:'#c1a86a',b:'#725a55',media:'cable-car'},
  {name:'Driving',group:'Vehicle',desc:'Urban roads and long-distance travel',a:'#c68f72',b:'#424f57',media:'driving',featured:true},
  {name:'Train',group:'Rail',desc:'Extended rail journeys and landscapes',a:'#9c8a72',b:'#39474b',media:'train',featured:true},
  {name:'Cycling',group:'Ground',desc:'Fast egocentric motion on winding roads',a:'#88ad77',b:'#174d43',media:'cycling',featured:true},
  {name:'Static & Pan',group:'Static',desc:'Stable observation with local rotation',a:'#9b91a8',b:'#464256',media:'static-pan',featured:true},
  {name:'Skiing',group:'Ground',desc:'Dynamic descent through snowy terrain',a:'#93aec5',b:'#405c77',media:'skiing',featured:true},
  {name:'Escalator',group:'Ground',desc:'Mechanically constrained vertical travel',a:'#c9a477',b:'#704e43',media:'escalator'},
  {name:'Straight Walk',group:'Ground',desc:'Long, steady pedestrian translation',a:'#77a78a',b:'#234d43',media:'walking-straight'},
  {name:'Curved Walk',group:'Ground',desc:'A smooth pedestrian arc through a real scene',a:'#84a779',b:'#315748',media:'walking-curve'},
  {name:'L-turn Walk',group:'Ground',desc:'A clear right-angle pedestrian turn',a:'#6e9f8b',b:'#274a48',media:'walking-lturn'},
  {name:'S-curve Walk',group:'Ground',desc:'A continuous two-direction ground trajectory',a:'#799c87',b:'#304d45',media:'walking-scurve'},
  {name:'Winding Walk',group:'Ground',desc:'Repeated turns along a complex path',a:'#8aaa76',b:'#365245',media:'walking-winding'},
  {name:'Loop Drive',group:'Vehicle',desc:'Vehicle motion with a return trajectory',a:'#ba846e',b:'#4d4546',media:'driving-loop'},
  {name:'Ridge Flight',group:'Aerial',desc:'Aerial traversal over large-scale terrain',a:'#6f98ac',b:'#294d59',media:'drone-ridge'},
  {name:'Alpine Cable Car',group:'Aerial',desc:'Constrained elevated motion across a vista',a:'#b5a269',b:'#67564d',media:'cable-car-alpine'},
  {name:'Static Landscape',group:'Static',desc:'Long observation with subtle camera motion',a:'#958da1',b:'#45434f',media:'static-landscape'}
];
const wallColors=[['#496b70','#172f35'],['#9e8068','#3b433f'],['#6f9279','#21453c'],['#7d7590','#35344a'],['#b18b66','#4d443d']];
document.querySelectorAll('.wall-column').forEach((col,ci)=>{const cards=[...types,...types];cards.forEach((t,i)=>{const d=document.createElement('div');d.className='wall-card';d.style.setProperty('--a',wallColors[(i+ci)%wallColors.length][0]);d.style.setProperty('--b',wallColors[(i+ci)%wallColors.length][1]);d.innerHTML=`<video src="assets/videos/${t.media}.mp4" poster="assets/images/${t.media}.jpg" autoplay muted loop playsinline preload="metadata"></video><span>${t.name} · Sekai2</span>`;col.appendChild(d)})});
document.querySelector('#motion-pills').innerHTML=types.map(x=>`<span class="pill">${x.name}</span>`).join('');
const groups=['All','Aerial','Ground','Vehicle','Rail','Water','Static'];
const filters=document.querySelector('#filters');
filters.innerHTML=groups.map((x,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('');
const grid=document.querySelector('#dataset-grid');
function renderCards(group='All'){
  grid.innerHTML=types.filter(x=>group==='All'?x.featured:x.group===group).map((x,i)=>`<article class="data-card ${x.wide?'wide':''} reveal visible" data-case="${x.media}" tabindex="0" role="button" aria-label="Open ${x.name} case study"><div class="card-media" style="--ca:${x.a};--cb:${x.b}"><video src="assets/videos/${x.media}.mp4" poster="assets/images/${x.media}.jpg" autoplay muted loop playsinline preload="metadata"></video><span class="media-type">${x.group}</span><span class="inspect">View case ↗</span></div><div class="card-body"><div><h3>${x.name}</h3><small>Video · Pose · Caption</small></div><p>${x.desc}</p></div></article>`).join('')
}
renderCards();filters.addEventListener('click',e=>{if(!e.target.matches('.filter'))return;filters.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderCards(e.target.dataset.filter)});
const fields=[['subject_motion','A drone advances steadily above a clear river as the channel bends through the valley.'],['environment_motion','Sunlight flickers across flowing water while foliage moves gently along both banks.'],['static_scene','A shallow mountain river is enclosed by dense green forest, rocks, and narrow gravel banks.'],['camera_description','A stabilized aerial camera travels forward at low altitude, following the river corridor.'],['full_prompt','A continuous low-altitude aerial journey follows a bright forest river and reveals its changing bends, banks, and surrounding terrain.']];
document.querySelector('#field-list').innerHTML=fields.map(x=>`<div class="field"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('');
const segColors=['#386889','#51978e','#78aa78','#dda044','#ca6a4f','#7c5ba8'];document.querySelector('#segment-strip').innerHTML=segColors.map((c,i)=>`<span class="segment" style="background:${c}" title="Segment ${i+1}"></span>`).join('');
const timeline=document.querySelector('#timeline'),readout=document.querySelector('#time-readout'),longVideo=document.querySelector('#long-video'),longPlay=document.querySelector('#long-play');
function showTime(n){n=Math.max(0,Math.min(120,Math.round(n)));readout.textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
timeline.addEventListener('input',()=>{const n=+timeline.value;showTime(n);if(Number.isFinite(longVideo.duration))longVideo.currentTime=Math.min(n,longVideo.duration-.05)});
longVideo.addEventListener('timeupdate',()=>{if(!timeline.matches(':active')){timeline.value=Math.min(120,longVideo.currentTime);showTime(longVideo.currentTime)}});
longVideo.addEventListener('play',()=>{longPlay.textContent='Ⅱ';longPlay.classList.add('playing')});longVideo.addEventListener('pause',()=>{longPlay.textContent='▶';longPlay.classList.remove('playing')});longPlay.addEventListener('click',()=>longVideo.paused?longVideo.play():longVideo.pause());
const trajectoryChoices=[['Drone','drone'],['Walking','walking'],['Driving','driving'],['Cycling','cycling'],['Boat','boat']];
const trajectoryPoseSources={walking:'walking-winding',driving:'driving-loop'};
const tabs=document.querySelector('#trajectory-tabs');tabs.innerHTML=trajectoryChoices.map(([name,key],i)=>`<button class="trajectory-tab ${i===0?'active':''}" data-case="${key}">${name}</button>`).join('');
let homepagePoseViewer=null;
function loadHomepageTrajectory(key){const item=caseData[trajectoryPoseSources[key]||key];if(!item?.pose3d)return;document.querySelector('#trajectory-case-name').textContent=types.find(x=>x.media===key)?.name||key;const video=document.querySelector('#trajectory-video');video.src=`assets/videos/pose-overlay-${key}.webm`;video.poster=`assets/images/pose-overlay-${key}.jpg`;video.play().catch(()=>{});if(!homepagePoseViewer){homepagePoseViewer=new PoseViewer(document.querySelector('#trajectory-viewer'));homepagePoseViewer.init()}homepagePoseViewer.loadTrajectory(item.pose3d);homepagePoseViewer.setShowFrustums(true);const startFrame=Math.round(item.preview_start_s/item.pose3d.duration*(item.pose3d.num_frames-1));homepagePoseViewer.setCurrentFrame(startFrame);homepagePoseViewer.snapToCameraView(startFrame);homepagePoseViewer._onResize()}
tabs.addEventListener('click',e=>{if(!e.target.matches('button'))return;tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');loadHomepageTrajectory(e.target.dataset.case)});
document.querySelector('#trajectory-video').addEventListener('timeupdate',e=>{const active=tabs.querySelector('.active')?.dataset.case,item=caseData[trajectoryPoseSources[active]||active];if(!homepagePoseViewer||!item)return;const sourceTime=item.preview_start_s+e.target.currentTime,frame=Math.round(sourceTime/item.pose3d.duration*(item.pose3d.num_frames-1));homepagePoseViewer.setCurrentFrame(frame)});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const captionCaseTabs=document.querySelector('#caption-case-tabs'),captionCaseExplorer=document.querySelector('#caption-case-explorer');let captionCases=[];
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function captionMarkup(value){return escapeHTML(value).replaceAll('&lt;camera&gt;','<mark>&lt;camera&gt;</mark>').replaceAll('&lt;/camera&gt;','<mark>&lt;/camera&gt;</mark>')}
function renderCaptionCase(id){const item=captionCases.find(x=>x.id===id)||captionCases[0];if(!item)return;captionCaseTabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.case===item.id));const points=item.trajectory.map(([x,y])=>`${8+x*84},${8+y*84}`).join(' '),fields=Object.entries(item.overall).map(([key,value])=>`<div class="web-caption-field"><b>${key}</b><p>${captionMarkup(value)}</p></div>`).join(''),segments=item.segments.map((segment,index)=>{const color=['#315B7D','#438C8C','#6DAA72','#D49A45','#C7674F','#7C5AA6','#476A9F','#609B76'][index%8];return `<div class="web-caption-segment" style="--segment-color:${color}"><b>S${index} · ${segment.time.join('–')}s · ${escapeHTML(segment.path||'continuous')}</b><p>${escapeHTML(segment.text)}</p></div>`}).join(''),timeline=item.segments.map((segment,index)=>{const color=['#315B7D','#438C8C','#6DAA72','#D49A45','#C7674F','#7C5AA6','#476A9F','#609B76'][index%8],width=(segment.time[1]-segment.time[0])/item.duration*100;return `<span style="width:${width}%;background:${color}">${segment.time.join('–')}s</span>`}).join('');captionCaseExplorer.innerHTML=`<div class="web-case-head"><div><span>Case ${item.id}</span><h3>${escapeHTML(item.shape)}</h3></div><p>${escapeHTML(item.dataset)} · ${Math.round(item.duration)} s · ${item.segments.length} segments</p></div><div class="web-case-frames">${item.frames.map((src,index)=>`<figure><img src="${src}" alt="Case ${item.id} at ${item.frame_times[index]} seconds" loading="lazy"><figcaption>t=${item.frame_times[index]}s</figcaption></figure>`).join('')}</div><div class="web-case-main"><div class="web-pose-card"><div class="web-card-title"><b>ViPE trajectory</b><span>bird's-eye view · color encodes time</span></div><svg viewBox="0 0 100 100" role="img" aria-label="Camera trajectory"><defs><linearGradient id="web-pose-gradient"><stop offset="0" stop-color="#315B7D"/><stop offset=".35" stop-color="#438C8C"/><stop offset=".7" stop-color="#D49A45"/><stop offset="1" stop-color="#7C5AA6"/></linearGradient></defs><polyline points="${points}"/><circle cx="${8+item.trajectory[0][0]*84}" cy="${8+item.trajectory[0][1]*84}" r="2.2"/><text x="${8+item.trajectory.at(-1)[0]*84}" y="${8+item.trajectory.at(-1)[1]*84}" class="web-pose-star">★</text></svg><div class="web-pose-legend"><span>● start</span><span>★ end</span></div></div><div class="web-global-card"><div class="web-card-title"><b>Global annotation</b><span>structured clip-level semantics</span></div><div class="web-controlled">${Object.values(item.attributes).filter(Boolean).map(x=>`<span>${escapeHTML(String(x).replaceAll('_',' '))}</span>`).join('')}</div><div class="web-caption-fields">${fields}</div></div></div><div class="web-temporal"><div class="web-card-title"><b>Temporally grounded annotations</b><span>segments[*].short_prompt · camera_path</span></div><div class="web-segment-timeline">${timeline}</div><div>${segments}</div></div>`}
fetch('assets/data/caption_cases.json').then(r=>r.json()).then(data=>{captionCases=data;captionCaseTabs.innerHTML=data.map((item,index)=>`<button class="caption-case-tab ${index===0?'active':''}" data-case="${item.id}"><span>${item.dataset}</span>${escapeHTML(item.shape)}</button>`).join('');renderCaptionCase(data[0]?.id)});captionCaseTabs.addEventListener('click',e=>{const button=e.target.closest('button');if(button)renderCaptionCase(button.dataset.case)});
let panoramicCases=[],panoramicExpanded=false,panoramicFilter='All';
const reconstructionGrid=document.querySelector('#reconstruction-grid'),reconstructionFilters=document.querySelector('#reconstruction-filters'),reconstructionMore=document.querySelector('#reconstruction-more');
function renderPanoramicCases(){const filtered=panoramicCases.filter(x=>panoramicFilter==='All'||x.motion===panoramicFilter),shown=panoramicExpanded?filtered:filtered.slice(0,12);reconstructionGrid.innerHTML=shown.map(x=>`<a class="reconstruction-card" href="${x.image}" target="_blank" rel="noreferrer"><div class="reconstruction-media"><img src="${x.image}" alt="${x.scene}, ${x.motion} panoramic reconstruction" loading="lazy"></div><div><b>${x.scene}</b><span>${x.motion.replaceAll('-',' ')}</span></div></a>`).join('');reconstructionMore.hidden=filtered.length<=12;reconstructionMore.textContent=panoramicExpanded?'Show selected cases only':`Show all ${filtered.length} reconstructions`}
fetch('assets/data/panoramic_cases.json').then(r=>r.json()).then(data=>{panoramicCases=data;const motions=['All',...new Set(data.map(x=>x.motion))];reconstructionFilters.innerHTML=motions.map((x,i)=>`<button class="recon-filter ${i===0?'active':''}" data-motion="${x}">${x.replaceAll('-',' ')}</button>`).join('');renderPanoramicCases()});
reconstructionFilters.addEventListener('click',e=>{if(!e.target.matches('button'))return;reconstructionFilters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');panoramicFilter=e.target.dataset.motion;panoramicExpanded=false;renderPanoramicCases()});reconstructionMore.addEventListener('click',()=>{panoramicExpanded=!panoramicExpanded;renderPanoramicCases()});

let caseData={};fetch('assets/data/cases.json').then(r=>r.json()).then(data=>{caseData=data;loadHomepageTrajectory('drone')});
const modal=document.querySelector('#case-modal'),modalVideo=document.querySelector('#modal-video');
let modalPoseViewer=null,activeCase=null;
function openCase(key){const item=caseData[key];if(!item)return;activeCase=item;const type=types.find(x=>x.media===key);document.querySelector('#modal-title').textContent=type?.name||key;document.querySelector('#modal-meta').textContent=`${item.dataset} · ${item.clip} · preview from t=${item.preview_start_s}s`;modalVideo.src=item.video;modalVideo.poster=item.poster;document.querySelector('#modal-attributes').innerHTML=Object.entries(item.attributes).filter(([,v])=>v).map(([k,v])=>`<span><small>${k.replaceAll('_',' ')}</small>${String(v).replaceAll('_',' ')}</span>`).join('');document.querySelector('#modal-fields').innerHTML=Object.entries(item.overall).filter(([,v])=>v).map(([k,v])=>`<div class="modal-field"><b>${k}</b><p>${v}</p></div>`).join('');document.querySelector('#modal-segments').innerHTML=item.segments.map((s,i)=>`<div class="modal-segment"><b>S${i} · ${s.time?.join('–')}s${s.path?' · '+s.path.replaceAll('_',' '):''}</b><p>${s.text}</p></div>`).join('');modal.showModal();requestAnimationFrame(()=>{if(!modalPoseViewer){modalPoseViewer=new PoseViewer(document.querySelector('#modal-pose-3d'));modalPoseViewer.init()}modalPoseViewer.loadTrajectory(item.pose3d);modalPoseViewer.setShowFrustums(document.querySelector('#pose-frustums').checked);modalPoseViewer._onResize()});modalVideo.play().catch(()=>{})}
grid.addEventListener('click',e=>{const card=e.target.closest('.data-card');if(card)openCase(card.dataset.case)});grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.data-card'))openCase(e.target.dataset.case)});document.querySelector('#modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('close',()=>{modalVideo.pause();modalVideo.removeAttribute('src');modalVideo.load()});modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
modalVideo.addEventListener('timeupdate',()=>{if(!modalPoseViewer||!activeCase)return;const pose=activeCase.pose3d,sourceTime=activeCase.preview_start_s+modalVideo.currentTime,frame=Math.round(sourceTime/pose.duration*(pose.num_frames-1));modalPoseViewer.setCurrentFrame(frame)});document.querySelector('#pose-frustums').addEventListener('change',e=>modalPoseViewer?.setShowFrustums(e.target.checked));document.querySelector('#pose-follow').addEventListener('change',e=>modalPoseViewer?.setFollowMode(e.target.checked));document.querySelector('#pose-reset').addEventListener('click',()=>modalPoseViewer?.resetCamera());
