const types=[
  {name:'Drone',group:'Aerial',desc:'Ascending, orbiting, and long-range flight',a:'#7298a8',b:'#254e54',media:'drone',wide:true},
  {name:'Walking',group:'Ground',desc:'First-person paths through real places',a:'#8caf8e',b:'#315b50',media:'walking'},
  {name:'Boat',group:'Water',desc:'Waterborne motion at multiple scales',a:'#79aebd',b:'#24526a',media:'boat',wide:true},
  {name:'Cable Car',group:'Aerial',desc:'Vertical motion and distant vistas',a:'#c1a86a',b:'#725a55',media:'cable-car'},
  {name:'Driving',group:'Vehicle',desc:'Urban roads and long-distance travel',a:'#c68f72',b:'#424f57',media:'driving'},
  {name:'Train',group:'Vehicle',desc:'Extended rail journeys and landscapes',a:'#9c8a72',b:'#39474b',media:'train'},
  {name:'Cycling',group:'Ground',desc:'Fast egocentric motion on winding roads',a:'#88ad77',b:'#174d43',media:'cycling'},
  {name:'Static & Pan',group:'Static',desc:'Stable observation with local rotation',a:'#9b91a8',b:'#464256',media:'static-pan'},
  {name:'Skiing',group:'Ground',desc:'Dynamic descent through snowy terrain',a:'#93aec5',b:'#405c77',media:'skiing'},
  {name:'Escalator',group:'Ground',desc:'Mechanically constrained vertical travel',a:'#c9a477',b:'#704e43',media:'escalator'}
];
const wallColors=[['#496b70','#172f35'],['#9e8068','#3b433f'],['#6f9279','#21453c'],['#7d7590','#35344a'],['#b18b66','#4d443d']];
document.querySelectorAll('.wall-column').forEach((col,ci)=>{const cards=[...types,...types];cards.forEach((t,i)=>{const d=document.createElement('div');d.className='wall-card';d.style.setProperty('--a',wallColors[(i+ci)%wallColors.length][0]);d.style.setProperty('--b',wallColors[(i+ci)%wallColors.length][1]);d.innerHTML=`<video src="assets/videos/${t.media}.mp4" poster="assets/images/${t.media}.jpg" autoplay muted loop playsinline preload="metadata"></video><span>${t.name} · Sekai2</span>`;col.appendChild(d)})});
document.querySelector('#motion-pills').innerHTML=types.map(x=>`<span class="pill">${x.name}</span>`).join('');
const groups=['All','Aerial','Ground','Vehicle','Water','Static'];
const filters=document.querySelector('#filters');
filters.innerHTML=groups.map((x,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('');
const grid=document.querySelector('#dataset-grid');
function renderCards(group='All'){
  grid.innerHTML=types.filter(x=>group==='All'||x.group===group).map((x,i)=>`<article class="data-card ${x.wide?'wide':''} reveal visible" data-case="${x.media}" tabindex="0" role="button" aria-label="Open ${x.name} case study"><div class="card-media" style="--ca:${x.a};--cb:${x.b}"><video src="assets/videos/${x.media}.mp4" poster="assets/images/${x.media}.jpg" autoplay muted loop playsinline preload="metadata"></video><span class="media-type">${x.group}</span><span class="inspect">View case ↗</span></div><div class="card-body"><div><h3>${x.name}</h3><small>Video · Pose · Caption</small></div><p>${x.desc}</p></div></article>`).join('')
}
renderCards();filters.addEventListener('click',e=>{if(!e.target.matches('.filter'))return;filters.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderCards(e.target.dataset.filter)});
const fields=[['subject_motion','A drone advances steadily above a clear river as the channel bends through the valley.'],['environment_motion','Sunlight flickers across flowing water while foliage moves gently along both banks.'],['static_scene','A shallow mountain river is enclosed by dense green forest, rocks, and narrow gravel banks.'],['camera_description','A stabilized aerial camera travels forward at low altitude, following the river corridor.'],['full_prompt','A continuous low-altitude aerial journey follows a bright forest river and reveals its changing bends, banks, and surrounding terrain.']];
document.querySelector('#field-list').innerHTML=fields.map(x=>`<div class="field"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('');
const segColors=['#386889','#51978e','#78aa78','#dda044','#ca6a4f','#7c5ba8'];document.querySelector('#segment-strip').innerHTML=segColors.map((c,i)=>`<span class="segment" style="background:${c}" title="Segment ${i+1}"></span>`).join('');
const timeline=document.querySelector('#timeline'),readout=document.querySelector('#time-readout'),longVideo=document.querySelector('#long-video'),longPlay=document.querySelector('#long-play');
function showTime(n){n=Math.max(0,Math.min(120,Math.round(n)));readout.textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
timeline.addEventListener('input',()=>{const n=+timeline.value;showTime(n);if(Number.isFinite(longVideo.duration))longVideo.currentTime=Math.min(n,longVideo.duration-.05)});
longVideo.addEventListener('timeupdate',()=>{if(!timeline.matches(':active')){timeline.value=Math.min(120,longVideo.currentTime);showTime(longVideo.currentTime)}});
longVideo.addEventListener('play',()=>{longPlay.textContent='Ⅱ';longPlay.classList.add('playing')});longVideo.addEventListener('pause',()=>{longPlay.textContent='▶';longPlay.classList.remove('playing')});longPlay.addEventListener('click',()=>longVideo.paused?longVideo.play():longVideo.pause());
const trajectoryChoices=[['Drone','drone'],['Walking','walking'],['Driving','driving'],['Cycling','cycling'],['Boat','boat']];
const tabs=document.querySelector('#trajectory-tabs');tabs.innerHTML=trajectoryChoices.map(([name,key],i)=>`<button class="trajectory-tab ${i===0?'active':''}" data-case="${key}">${name}</button>`).join('');
let homepagePoseViewer=null;
function loadHomepageTrajectory(key){const item=caseData[key];if(!item?.pose3d)return;document.querySelector('#trajectory-case-name').textContent=types.find(x=>x.media===key)?.name||key;if(!homepagePoseViewer){homepagePoseViewer=new PoseViewer(document.querySelector('#trajectory-viewer'));homepagePoseViewer.init()}homepagePoseViewer.loadTrajectory(item.pose3d);homepagePoseViewer.setShowFrustums(true);homepagePoseViewer._onResize()}
tabs.addEventListener('click',e=>{if(!e.target.matches('button'))return;tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');loadHomepageTrajectory(e.target.dataset.case)});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
document.querySelectorAll('.study-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.study-tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');const key=button.dataset.study,path=`assets/images/caption-case-${key}.jpg`,image=document.querySelector('#study-image');image.src=path;image.alt=key==='drone'?'Sekai2 drone video, pose, and caption case study':'Sekai2 walking video, pose, and caption case study';document.querySelector('#study-link').href=path}));
document.querySelectorAll('.recon-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.recon-tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');const path=`assets/images/panoramic-reconstruction-${button.dataset.recon}.jpg`;document.querySelector('#recon-image').src=path;document.querySelector('#recon-link').href=path}));

let caseData={};fetch('assets/data/cases.json').then(r=>r.json()).then(data=>{caseData=data;loadHomepageTrajectory('drone')});
const modal=document.querySelector('#case-modal'),modalVideo=document.querySelector('#modal-video');
let modalPoseViewer=null,activeCase=null;
function openCase(key){const item=caseData[key];if(!item)return;activeCase=item;const type=types.find(x=>x.media===key);document.querySelector('#modal-title').textContent=type?.name||key;document.querySelector('#modal-meta').textContent=`${item.dataset} · ${item.clip} · preview from t=${item.preview_start_s}s`;modalVideo.src=item.video;modalVideo.poster=item.poster;document.querySelector('#modal-attributes').innerHTML=Object.entries(item.attributes).filter(([,v])=>v).map(([k,v])=>`<span><small>${k.replaceAll('_',' ')}</small>${String(v).replaceAll('_',' ')}</span>`).join('');document.querySelector('#modal-fields').innerHTML=Object.entries(item.overall).filter(([,v])=>v).map(([k,v])=>`<div class="modal-field"><b>${k}</b><p>${v}</p></div>`).join('');document.querySelector('#modal-segments').innerHTML=item.segments.map((s,i)=>`<div class="modal-segment"><b>S${i} · ${s.time?.join('–')}s${s.path?' · '+s.path.replaceAll('_',' '):''}</b><p>${s.text}</p></div>`).join('');modal.showModal();requestAnimationFrame(()=>{if(!modalPoseViewer){modalPoseViewer=new PoseViewer(document.querySelector('#modal-pose-3d'));modalPoseViewer.init()}modalPoseViewer.loadTrajectory(item.pose3d);modalPoseViewer.setShowFrustums(document.querySelector('#pose-frustums').checked);modalPoseViewer._onResize()});modalVideo.play().catch(()=>{})}
grid.addEventListener('click',e=>{const card=e.target.closest('.data-card');if(card)openCase(card.dataset.case)});grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.data-card'))openCase(e.target.dataset.case)});document.querySelector('#modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('close',()=>{modalVideo.pause();modalVideo.removeAttribute('src');modalVideo.load()});modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
modalVideo.addEventListener('timeupdate',()=>{if(!modalPoseViewer||!activeCase)return;const pose=activeCase.pose3d,sourceTime=activeCase.preview_start_s+modalVideo.currentTime,frame=Math.round(sourceTime/pose.duration*(pose.num_frames-1));modalPoseViewer.setCurrentFrame(frame)});document.querySelector('#pose-frustums').addEventListener('change',e=>modalPoseViewer?.setShowFrustums(e.target.checked));document.querySelector('#pose-follow').addEventListener('change',e=>modalPoseViewer?.setFollowMode(e.target.checked));document.querySelector('#pose-reset').addEventListener('click',()=>modalPoseViewer?.resetCamera());
